Repository munich-quantum-toolkit/core, pull requests merged in 2022-10, with the labels that each got.

#201 🚸 Check whether a logical qubit is contained in a circuit
  include/QuantumComputation.hpp
  src/QuantumComputation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement

#202 🐛 Fix ancillary and garbage tracking when adding ancilla qubits
  src/QuantumComputation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: bug

#206 Update version of publish action
  .github/workflows/deploy.yml
Labels: enhancement

#207 🐛⚡ Enable `qiskit-terra>=0.22.0` compatibility
  mqt/qfr/qiskit/QuantumCircuit.hpp
Labels: bug, enhancement

#208 ♻️📦 Modernize Python packaging
  CMakeLists.txt
  mqt/qfr/CMakeLists.txt
  mqt/qfr/bindings.cpp
  pyproject.toml
  setup.py
Labels: enhancement
