Repository munich-quantum-toolkit/core, pull requests merged in 2023-08, with the labels that each got.

#385 🐛 Fix DD node leak
  include/dd/Package.hpp
  test/dd/test_package.cpp
Labels: fix, DD, c++

#386 🐛 Fix Compute Table Performance
  include/dd/ComputeTable.hpp
  include/dd/Package.hpp
  include/dd/UnaryComputeTable.hpp
  test/dd/test_package.cpp
Labels: fix, DD, c++

#391 Add w state implementation
  include/algorithms/WState.hpp
  src/CMakeLists.txt
  src/algorithms/WState.cpp
  test/CMakeLists.txt
  test/algorithms/test_wstate.cpp
Labels: feature, c++

#393 🔥 Remove Snapshot and ShowProbabilities instructions from MQT Core
  include/dd/FunctionalityConstruction.hpp
  include/dd/Operations.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/OpType.hpp
  src/CircuitOptimizer.cpp
  src/dd/Operations.cpp
  src/operations/NonUnitaryOperation.cpp
  src/parsers/QASMParser.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: refactor, code quality, Core, c++

#394 ♻️ Refactor handling of Barrier operations
  include/CircuitOptimizer.hpp
  include/QuantumComputation.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/OpType.hpp
  include/operations/Operation.hpp
  src/CircuitOptimizer.cpp
  src/QuantumComputation.cpp
  src/operations/NonUnitaryOperation.cpp
  src/operations/Operation.cpp
  src/operations/StandardOperation.cpp
  src/parsers/QASMParser.cpp
  test/dd/test_dd_functionality.cpp
Labels: refactor, code quality, Core, c++

#395 ⚡ use 2x faster black mirror
  .pre-commit-config.yaml
Labels: usability, python

#396 🧑‍💻 Extensive and Reusable CI/CD Setup
  .cirrus.yml
  .github/codecov.yml
  .github/contributing.md
  .github/contributing.rst
  .github/support.md
  .github/support.rst
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/emulated-wheels.yml
  .github/workflows/python-ci.yml
  .github/workflows/reusable-change-detection.yml
  .github/workflows/reusable-code-ql-cpp.yml
  .github/workflows/reusable-code-ql-python.yml
  .github/workflows/reusable-code-ql.yml
  .github/workflows/reusable-cpp-ci.yml
  .github/workflows/reusable-cpp-coverage.yml
  .github/workflows/reusable-cpp-linter.yml
  .github/workflows/reusable-cpp-tests-macos.yml
  .github/workflows/reusable-cpp-tests-ubuntu.yml
  .github/workflows/reusable-cpp-tests-windows.yml
  .github/workflows/reusable-python-ci.yml
  .github/workflows/reusable-python-coverage.yml
  .github/workflows/reusable-python-linter.yml
  .github/workflows/reusable-python-packaging.yml
  .github/workflows/reusable-python-tests.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  README.md
  pyproject.toml
  src/python/CMakeLists.txt
Labels: usability, refactor, continuous integration, Core

#397 📦 Enable target support from scikit-build-core
  .github/workflows/reusable-change-detection.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies, Core, python, packaging

#399 ♻️ Refactor `NonUnitaryOperation` class to simplify target handling
  include/operations/NonUnitaryOperation.hpp
  src/operations/NonUnitaryOperation.cpp
Labels: refactor, Core, c++

#401 🔧 Add policy max to CMake minimum required version
  .github/workflows/reusable-change-detection.yml
  CMakeLists.txt
Labels: usability, c++

#402 🩹 Remove Barrier check from actsOn method
  include/operations/Operation.hpp
  test/dd/test_dd_functionality.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: fix, Core, c++

#407 🚸 Make reusable workflows more generic
  .cirrus.yml
  .github/codecov.yml
  .github/codeql-config.yml
  .github/dependabot.yml
  .github/workflows/release-drafter.yml
  .github/workflows/reusable-change-detection.yml
  .github/workflows/reusable-code-ql-cpp.yml
  .github/workflows/reusable-code-ql-python.yml
  .github/workflows/reusable-code-ql.yml
  .github/workflows/reusable-cpp-ci.yml
  .github/workflows/reusable-cpp-coverage.yml
  .github/workflows/reusable-cpp-linter.yml
  .github/workflows/reusable-cpp-tests-macos.yml
  .github/workflows/reusable-cpp-tests-ubuntu.yml
  .github/workflows/reusable-cpp-tests-windows.yml
  .github/workflows/reusable-python-ci.yml
  .github/workflows/reusable-python-coverage.yml
  .github/workflows/reusable-python-linter.yml
  .github/workflows/reusable-python-packaging.yml
  .github/workflows/reusable-python-tests.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  README.md
  cmake/CompilerOptions.cmake
  cmake/StandardProjectSettings.cmake
  docs/index.md
  noxfile.py
  pyproject.toml
  test/python/constraints.txt
Labels: github_actions, usability, continuous integration
