Repository munich-quantum-toolkit/core, pull requests merged in 2023-11, with the labels that each got.

#466 Added RZZ, RXX, RZX, and RYY to ZX-diagrams
  include/zx/FunctionalityConstruction.hpp
  src/zx/FunctionalityConstruction.cpp
  test/zx/test_zx_functionality.cpp
Labels: enhancement, ZX, c++

#472 🚨 small ruff updates
  docs/conf.py
  pyproject.toml
  src/mqt/core/_compat/typing.py
  src/mqt/core/plugins/qiskit.py
Labels: code quality

#474 🐛 Fix recursive circuit flattening
  src/CircuitOptimizer.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: fix, Core, c++

#473 ✨ Circuit optimisation for replacing Toffoli gates with MCZ gates and Hadamards
  include/CircuitOptimizer.hpp
  src/CircuitOptimizer.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement, Core, c++

#475 🐛⚡ fix and speed up Kronecker product for DDs
  include/dd/Package.hpp
  test/dd/test_package.cpp
Labels: enhancement, fix, DD, c++

#476 🐛 Miscellaneous fixes for qubit and register handling
  include/QuantumComputation.hpp
  src/QuantumComputation.cpp
  src/mqt/core/plugins/qiskit.py
  src/operations/NonUnitaryOperation.cpp
  test/unittests/test_io.cpp
Labels: fix, Core, c++

#477 ⬆️ update `scikit-build-core`
  .pre-commit-config.yaml
  noxfile.py
  pyproject.toml
  test/python/constraints.txt
Labels: dependencies, python, packaging

#469 📝 added project acknowledgements
  README.md
  docs/_static/custom.css
  docs/_static/erc_dark.svg
  docs/_static/erc_light.svg
  docs/_static/logo-bavaria.svg
  docs/_static/logo-mqv.svg
  docs/_static/tum_dark.svg
  docs/_static/tum_light.svg
  docs/_templates/page.html
  docs/conf.py
  docs/index.md
  extern/mqt_dark.png
  extern/mqt_light.png
Labels: documentation

#478 🐛 fix compiler errors in GCC-10 due to abstract return type
  src/python/operations/register_operation.cpp
Labels: fix, Core, c++

#481 ✨ support ECR and DCX gate in ZX library
  include/zx/FunctionalityConstruction.hpp
  src/zx/FunctionalityConstruction.cpp
  test/zx/test_zx_functionality.cpp
Labels: enhancement, ZX, c++

#480 🚚 move `check-sdist` from pre-commit to CI
  .github/workflows/reusable-python-linter.yml
  .pre-commit-config.yaml
Labels: usability, code quality, continuous integration

#483 ✨ add Scientific Python's repo-review
  .pre-commit-config.yaml
  pyproject.toml
Labels: code quality

#460 :sparkles: added inverse gate for iSWAP
  include/QuantumComputation.hpp
  include/dd/Operations.hpp
  include/operations/OpType.hpp
  include/parsers/qasm_parser/Parser.hpp
  src/mqt/core/_core/__init__.pyi
  src/mqt/core/_core/operations.pyi
  src/operations/StandardOperation.cpp
  src/python/operations/register_optype.cpp
  test/dd/test_dd_functionality.cpp
  test/unittests/test_io.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement, Core, c++
