Repository munich-quantum-toolkit/core, pull requests merged in 2023-03, with the labels that each got.

#277 🩹 Fix strip idle qubits corner case
  src/QuantumComputation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: bug

#279 🩹 Allow removing logical qubits used in the output permutation by force
  src/QuantumComputation.cpp
Labels: bug

#284 ♻️ Refactor global phase handling
  include/QuantumComputation.hpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement

#285 ⏪ Add back a `opTypeFromString` method
  include/operations/OpType.hpp
  test/unittests/test_qfr_functionality.cpp
Labels: usability

#286 Add opaque teleportation gate
  include/parsers/qasm_parser/Parser.hpp
  src/QuantumComputation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement
