Repository munich-quantum-toolkit/core, pull requests merged in 2023-09, with the labels that each got.

#415 Fix makeDDFromMatrix Issue in Asymmetrical Matrices
  include/dd/Package.hpp
  test/dd/test_package.cpp
Labels: fix, DD, c++

#417 🐛 Fix inexact QPE construction
  src/algorithms/QPE.cpp
Labels: fix, Core, c++

#418 🚸 Better statistics tracking in DD Package
  include/dd/ComputeTable.hpp
  include/dd/DensityNoiseTable.hpp
  include/dd/MemoryManager.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Package.hpp
  include/dd/RealNumberUniqueTable.hpp
  include/dd/StochasticNoiseOperationTable.hpp
  include/dd/UnaryComputeTable.hpp
  include/dd/UniqueTable.hpp
  include/dd/UniqueTableStatistics.hpp
  include/dd/statistics/MemoryManagerStatistics.hpp
  include/dd/statistics/PackageStatistics.hpp
  include/dd/statistics/Statistics.hpp
  include/dd/statistics/TableStatistics.hpp
  include/dd/statistics/UniqueTableStatistics.hpp
  src/dd/CMakeLists.txt
  src/dd/ComplexNumbers.cpp
  src/dd/MemoryManager.cpp
  src/dd/RealNumberUniqueTable.cpp
  src/dd/UniqueTableStatistics.cpp
  src/dd/statistics/MemoryManagerStatistics.cpp
  src/dd/statistics/Statistics.cpp
  src/dd/statistics/TableStatistics.cpp
  src/dd/statistics/UniqueTableStatistics.cpp
  test/dd/test_complex.cpp
  test/dd/test_package.cpp
Labels: usability, DD, c++

#419 🚸 Follow-up for DD statistics
  include/dd/UniqueTable.hpp
  include/dd/statistics/PackageStatistics.hpp
  include/dd/statistics/UniqueTableStatistics.hpp
  src/dd/RealNumberUniqueTable.cpp
  src/dd/statistics/MemoryManagerStatistics.cpp
  src/dd/statistics/TableStatistics.cpp
  src/dd/statistics/UniqueTableStatistics.cpp
  test/dd/test_package.cpp
Labels: usability, DD, c++

#422 🐛 Fix broken `manylinux` wheels
  pyproject.toml
Labels: continuous integration, fix, packaging

#411 Add `addControl`, `clearControls`, `removeControl` functions on Operation
  include/operations/ClassicControlledOperation.hpp
  include/operations/CompoundOperation.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/Operation.hpp
  include/operations/StandardOperation.hpp
  src/CircuitOptimizer.cpp
  src/operations/NonUnitaryOperation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: feature, Core, c++

#416 Add invert functionality for quantum operations
  include/operations/ClassicControlledOperation.hpp
  include/operations/CompoundOperation.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/Operation.hpp
  include/operations/StandardOperation.hpp
  include/operations/SymbolicOperation.hpp
  src/operations/StandardOperation.cpp
  src/operations/SymbolicOperation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: feature, Core, c++

#425 🚨 fix compiler warnings for `getControls` override
  include/operations/NonUnitaryOperation.hpp
  test/unittests/test_qfr_functionality.cpp
Labels: fix, Core, c++

#424 🚸 Small corrections for statistics tracking
  include/dd/UniqueTable.hpp
  src/dd/MemoryManager.cpp
  src/dd/statistics/MemoryManagerStatistics.cpp
  test/dd/test_complex.cpp
Labels: fix, DD, c++

#426 🐛 Fix identity handling in DD multiplication
  include/dd/Edge.hpp
  include/dd/Node.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Package.hpp
  src/dd/Edge.cpp
Labels: refactor, fix, DD, c++

#432 ♻️ switch back from nanobind to pybind
  .github/workflows/reusable-code-ql-python.yml
  .pre-commit-config.yaml
  include/python/pybind11.hpp
  noxfile.py
  pyproject.toml
  src/python/CMakeLists.txt
  src/python/module.cpp
Labels: Core, c++, python, packaging

#433 🩹 Reusable workflow corrections
  .github/workflows/reusable-code-ql-cpp.yml
  .github/workflows/reusable-code-ql-python.yml
  .github/workflows/reusable-python-packaging.yml
Labels: continuous integration, fix
