Repository munich-quantum-toolkit/core, pull requests merged in 2023-06, with the labels that each got.

#319 🔥 Remove MQT QFR Python package
  .flake8
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
  MANIFEST.in
  mqt/qfr/CMakeLists.txt
  mqt/qfr/__init__.py
  mqt/qfr/bindings.cpp
  mqt/qfr/pyqfr.pyi
  noxfile.py
  pyproject.toml
  setup.py
Labels: refactor

#322 👷⚡ speed up CI with independent coverage job
  .github/workflows/ci.yml
Labels: usability, continuous integration

#323 👨‍💻 introduce compiler cache
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  CMakeLists.txt
  cmake/Cache.cmake
Labels: usability, continuous integration

#324 👨‍💻 introduce `mold` as default linker under Linux
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: usability, continuous integration

#326 🚚 Move DD Package into Source Tree
  CMakeLists.txt
  extern/dd_package/.github/codecov.yml
  extern/dd_package/.github/workflows/ci.yml
  extern/dd_package/.github/workflows/codeql-analysis.yml
  extern/dd_package/CMakeLists.txt
  extern/dd_package/README.md
  extern/dd_package/test/CMakeLists.txt
  extern/dd_package/test/main.cpp
  include/dd/Complex.hpp
  include/dd/ComplexCache.hpp
  include/dd/ComplexNumbers.hpp
  include/dd/ComplexTable.hpp
  include/dd/ComplexValue.hpp
  include/dd/ComputeTable.hpp
  include/dd/Control.hpp
  include/dd/Definitions.hpp
  include/dd/DensityNoiseTable.hpp
  include/dd/Edge.hpp
  include/dd/Export.hpp
  include/dd/GateMatrixDefinitions.hpp
  include/dd/Node.hpp
  include/dd/Package.hpp
  include/dd/StochasticNoiseOperationTable.hpp
  include/dd/ToffoliTable.hpp
  include/dd/UnaryComputeTable.hpp
  include/dd/UniqueTable.hpp
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/dd/test_complex.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_package.cpp
Labels: refactor

#330 🚨 CodeQL Fixes
  include/dd/Definitions.hpp
  include/dd/Export.hpp
  include/dd/UniqueTable.hpp
Labels: code quality

#329 📦 Support Versioning in Git Archives
  .git_archival.txt
  .gitattributes
Labels: enhancement

#333 Actually Populate the Params list from Qobjs
  mqt/qfr/qiskit/QasmQobjExperiment.hpp
Labels: bug

#350 ✨ Add release drafter setup
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: usability, continuous integration

#351 ✨ add Issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
Labels: usability, continuous integration

#352 ✨ add community health files
  .github/contributing.rst
  .github/support.rst
Labels: documentation

#353 🔧 Disable IPO per default
  .github/workflows/ci.yml
  cmake/StandardProjectSettings.cmake
Labels: usability, continuous integration

#354 🔒 add security policy
  .github/SECURITY.md
Labels: documentation

#355 🩹 avoid header confusion
  src/CMakeLists.txt
  src/python/qiskit/QasmQobjExperiment.cpp
  src/python/qiskit/QuantumCircuit.cpp
Labels: fix, Core

#356 📝 Initial RtD setup
  .gitignore
  .readthedocs.yaml
  README.md
  docs/_static/mqt_dark.png
  docs/_static/mqt_light.png
  docs/conf.py
  docs/index.md
  docs/requirements.txt
  noxfile.py
Labels: documentation

#359 🎉🐍 Initial `mqt.core` Python Package Configuration
  .github/SECURITY.md
  .github/codecov.yml
  .github/matchers/pylint.json
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cpp-linter.yml
  .github/workflows/emulated-wheels.yml
  .github/workflows/python-ci.yml
  .github/workflows/release-drafter.yml
  .github/workflows/wheels.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
  include/python/nanobind.hpp
  noxfile.py
  pyproject.toml
  src/CMakeLists.txt
  src/mqt/core/__init__.py
  src/mqt/core/_core/__init__.pyi
  src/mqt/core/_version.pyi
  src/mqt/core/py.typed
  src/python/CMakeLists.txt
  src/python/module.cpp
  test/python/test_add.py
Labels: continuous integration, feature, Core, python

#361 🐛 Make MSVC work
  .github/workflows/ci.yml
  .github/workflows/python-ci.yml
  .github/workflows/wheels.yml
  .gitignore
  cmake/CompilerWarnings.cmake
  include/CircuitOptimizer.hpp
  include/QuantumComputation.hpp
  include/algorithms/GoogleRandomCircuitSampling.hpp
  include/dd/DDpackageConfig.hpp
  include/dd/Edge.hpp
  include/dd/Node.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Operations.hpp
  include/dd/Package.hpp
  include/dd/Package_fwd.hpp
  include/dd/UniqueTable.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/SymbolicOperation.hpp
  pyproject.toml
  src/CMakeLists.txt
  src/CircuitOptimizer.cpp
  src/QuantumComputation.cpp
  src/algorithms/GoogleRandomCircuitSampling.cpp
  src/algorithms/RandomCliffordCircuit.cpp
  src/dd/Edge.cpp
  src/dd/FunctionalityConstruction.cpp
  src/dd/Node.cpp
  src/ecc/Q18Surface.cpp
  src/ecc/Q3Shor.cpp
  src/ecc/Q5Laflamme.cpp
  src/ecc/Q7Steane.cpp
  src/ecc/Q9Shor.cpp
  src/ecc/Q9Surface.cpp
  src/operations/NonUnitaryOperation.cpp
  src/parsers/QASMParser.cpp
  src/parsers/QCParser.cpp
  src/parsers/RealParser.cpp
  src/parsers/TFCParser.cpp
  src/parsers/qasm_parser/Parser.cpp
  src/python/qiskit/QuantumCircuit.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_package.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: refactor, code quality, fix, DD, Core, c++

#363 🚸 Automatic discovery of nanobind when running outside `pip install`
  src/python/CMakeLists.txt
Labels: usability

#364 Cmake structure
  CMakeLists.txt
  cmake/CompilerOptions.cmake
  pyproject.toml
  src/CMakeLists.txt
  src/dd/CMakeLists.txt
  src/ecc/CMakeLists.txt
  src/zx/CMakeLists.txt
Labels: usability, c++

#365 ➕🪝 add new pre-commit hook for running ruff on Jupyter notebooks
  .pre-commit-config.yaml
Labels: usability, python
