Repository munich-quantum-toolkit/core, pull requests merged in 2023-12, with the labels that each got.

#495 ♻️ Revised qubit register handling
  src/QuantumComputation.cpp
  test/unittests/test_io.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: fix, Core, c++

#452 Benchmarking the DD package
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  docs/dd_package_evaluation.ipynb
  docs/index.md
  eval/CMakeLists.txt
  eval/eval_dd_package.cpp
  include/Definitions.hpp
  include/dd/Benchmark.hpp
  pyproject.toml
  src/dd/Benchmark.cpp
  src/dd/CMakeLists.txt
  src/mqt/core/evaluation.py
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_bernsteinvazirani.cpp
  test/algorithms/test_entanglement.cpp
  test/algorithms/test_grover.cpp
  test/algorithms/test_qft.cpp
  test/algorithms/test_qpe.cpp
  test/algorithms/test_random_clifford.cpp
  test/algorithms/test_wstate.cpp
  test/python/constraints.txt
  test/python/results_baseline.json
  test/python/results_feature.json
  test/python/test_evaluation.py
Labels: code quality, feature

#309 ✨ OpenQASM 3.0 support
  include/Definitions.hpp
  include/QuantumComputation.hpp
  include/operations/ClassicControlledOperation.hpp
  include/operations/CompoundOperation.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/Operation.hpp
  include/operations/StandardOperation.hpp
  include/operations/SymbolicOperation.hpp
  include/parsers/qasm3_parser/Exception.hpp
  include/parsers/qasm3_parser/Gate.hpp
  include/parsers/qasm3_parser/InstVisitor.hpp
  include/parsers/qasm3_parser/NestedEnvironment.hpp
  include/parsers/qasm3_parser/Parser.hpp
  include/parsers/qasm3_parser/Scanner.hpp
  include/parsers/qasm3_parser/Statement.hpp
  include/parsers/qasm3_parser/StdGates.hpp
  include/parsers/qasm3_parser/Token.hpp
  include/parsers/qasm3_parser/Types.hpp
  include/parsers/qasm3_parser/passes/CompilerPass.hpp
  include/parsers/qasm3_parser/passes/ConstEvalPass.hpp
  include/parsers/qasm3_parser/passes/TypeCheckPass.hpp
  include/parsers/qasm_parser/Parser.hpp
  include/parsers/qasm_parser/Scanner.hpp
  include/parsers/qasm_parser/Token.hpp
  include/zx/FunctionalityConstruction.hpp
  src/CMakeLists.txt
  src/QuantumComputation.cpp
  src/mqt/core/_core/__init__.pyi
  src/mqt/core/_core/operations.pyi
  src/operations/ClassicControlledOperation.cpp
  src/operations/NonUnitaryOperation.cpp
  src/operations/StandardOperation.cpp
  src/operations/SymbolicOperation.cpp
  src/parsers/QASM3Parser.cpp
  src/parsers/QASMParser.cpp
  src/parsers/QCParser.cpp
  src/parsers/RealParser.cpp
  src/parsers/TFCParser.cpp
  src/parsers/qasm3_parser/Parser.cpp
  src/parsers/qasm3_parser/Scanner.cpp
  src/parsers/qasm3_parser/Types.cpp
  src/parsers/qasm3_parser/passes/ConstEvalPass.cpp
  src/parsers/qasm3_parser/passes/TypeCheckPass.cpp
  src/parsers/qasm_parser/Parser.cpp
  src/parsers/qasm_parser/Scanner.cpp
  src/python/operations/register_operation.cpp
  src/python/register_quantum_computation.cpp
  src/zx/FunctionalityConstruction.cpp
  test/CMakeLists.txt
  test/circuits/test.qasm
  test/unittests/test_io.cpp
  test/unittests/test_qasm3_parser.cpp
  test/unittests/test_qfr_functionality.cpp
  test/zx/test_zx_functionality.cpp
Labels: feature, minor, Core

#499 🩹 properly reset tolerance in test
  src/parsers/qasm3_parser/passes/ConstEvalPass.cpp
  test/algorithms/test_wstate.cpp
Labels: fix, DD, c++

#498 ✨ Add support for OpenQASM 3.0 `else`
  include/Definitions.hpp
  include/operations/ClassicControlledOperation.hpp
  include/parsers/qasm3_parser/Statement.hpp
  include/parsers/qasm3_parser/passes/ConstEvalPass.hpp
  src/CMakeLists.txt
  src/operations/ClassicControlledOperation.cpp
  src/parsers/QASM3Parser.cpp
  src/parsers/qasm3_parser/Statement.cpp
  test/unittests/test_qasm3_parser.cpp
Labels: enhancement, Core, c++

#500 🚨 proper use of `std::enable_if` for SFINAE
  include/operations/Expression.hpp
Labels: fix, Core, c++

#501 ♻️⚡ Refactor and fine-tune DD normalization
  include/dd/Edge.hpp
  include/dd/Package.hpp
  src/dd/Edge.cpp
  test/dd/test_package.cpp
Labels: enhancement, refactor, DD, c++

#444 ♻️ Remove complex cache
  include/dd/CachedEdge.hpp
  include/dd/ComplexNumbers.hpp
  include/dd/ComplexValue.hpp
  include/dd/Edge.hpp
  include/dd/MemoryManager.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Package.hpp
  include/dd/statistics/PackageStatistics.hpp
  src/dd/CachedEdge.cpp
  src/dd/ComplexNumbers.cpp
  src/dd/Edge.cpp
  src/dd/MemoryManager.cpp
  test/algorithms/test_grover.cpp
  test/algorithms/test_qft.cpp
  test/dd/test_complex.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_package.cpp
Labels: enhancement, refactor, minor, DD, c++

#507 ⚡ Improved accuracy in complex number arithmetic
  include/dd/Complex.hpp
  include/dd/ComplexNumbers.hpp
  include/dd/ComplexValue.hpp
  include/dd/ComputeTable.hpp
  include/dd/Export.hpp
  include/dd/Package.hpp
  include/dd/RealNumber.hpp
  src/dd/Complex.cpp
  src/dd/ComplexValue.cpp
  src/dd/RealNumber.cpp
  src/dd/RealNumberUniqueTable.cpp
  src/dd/Simulation.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_package.cpp
Labels: enhancement, DD, c++

#508 🎨 provide `operator<<` overloads for scoped enums in ZX package
  include/zx/ZXDefinitions.hpp
  test/zx/test_zx.cpp
Labels: usability, ZX, c++

#509 Fix handling of output permutation and initial layout
  src/parsers/QASM3Parser.cpp
  test/unittests/test_qasm3_parser.cpp
Labels: fix, Core, c++
