Repository munich-quantum-toolkit/core, pull requests merged in 2023-10, with the labels that each got.

#434 ♻️ Trim `dd/Package.hpp`
  include/dd/CachedEdge.hpp
  include/dd/Complex.hpp
  include/dd/DDDefinitions.hpp
  include/dd/Edge.hpp
  include/dd/Node.hpp
  include/dd/Package.hpp
  include/dd/Simulation.hpp
  include/dd/UniqueTable.hpp
  src/dd/CMakeLists.txt
  src/dd/CachedEdge.cpp
  src/dd/Complex.cpp
  src/dd/Edge.cpp
  src/dd/Operations.cpp
  src/dd/Simulation.cpp
  test/CMakeLists.txt
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_entanglement.cpp
  test/algorithms/test_grover.cpp
  test/algorithms/test_qft.cpp
  test/algorithms/test_qpe.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
Labels: refactor, code quality, DD, c++

#437 🐛 Fix output permutation deduction
  src/python/qiskit/QuantumCircuit.cpp
Labels: fix, Core, python

#442 ⚡ Skip `symmetry` computation and 🔥 remove `transpose` method
  include/dd/DDpackageConfig.hpp
  include/dd/Node.hpp
  include/dd/Package.hpp
  include/dd/statistics/PackageStatistics.hpp
  test/dd/test_package.cpp
Labels: enhancement, DD, c++

#454 🩹 temporarily disable editable installs in nox jobs
  noxfile.py
  pyproject.toml
Labels: continuous integration, fix

#453 Fixing `QuantumComputation::dump` file name dot count check
  src/QuantumComputation.cpp
  test/unittests/test_io.cpp
Labels: fix, Core, c++

#448 ♻️ Replace static `zero` and `one` members with constexpr functions
  include/dd/Complex.hpp
  include/dd/ComplexNumbers.hpp
  include/dd/Edge.hpp
  include/dd/Export.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Package.hpp
  include/dd/RealNumber.hpp
  include/dd/UniqueTable.hpp
  src/dd/Complex.cpp
  src/dd/ComplexNumbers.cpp
  src/dd/Edge.cpp
  src/dd/FunctionalityConstruction.cpp
  src/dd/RealNumber.cpp
  test/dd/test_complex.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
Labels: code quality, DD, c++

#449 ♻️ simpler gate matrices
  include/dd/DDDefinitions.hpp
  include/dd/GateMatrixDefinitions.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Operations.hpp
  include/dd/Package.hpp
  src/dd/Simulation.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
Labels: code quality, DD, c++

#451 ⚡ Small unique table lookup improvement
  include/dd/Package.hpp
  include/dd/UniqueTable.hpp
  test/dd/test_package.cpp
  test/unittests/test_io.cpp
Labels: code quality, DD, c++

#456 ⚡ Small performance improvements to `RealNumberUniqueTable`
  src/dd/RealNumberUniqueTable.cpp
Labels: enhancement, DD, c++

#455 🎨 Miscellaneous code style improvements in DD package
  include/dd/Complex.hpp
  include/dd/ComplexNumbers.hpp
  include/dd/ComplexValue.hpp
  include/dd/Export.hpp
  include/dd/Node.hpp
  include/dd/NoiseFunctionality.hpp
  include/dd/Package.hpp
  include/dd/RealNumber.hpp
  src/dd/Complex.cpp
  src/dd/ComplexNumbers.cpp
  src/dd/ComplexValue.cpp
  src/dd/RealNumber.cpp
  src/operations/Operation.cpp
  test/algorithms/test_wstate.cpp
  test/dd/test_dd_noise_functionality.cpp
Labels: code quality, DD, c++

#457 ⚡ Completely eliminate temporary numbers borrowed from the cache
  include/dd/CachedEdge.hpp
  include/dd/Complex.hpp
  include/dd/ComplexNumbers.hpp
  include/dd/ComplexValue.hpp
  include/dd/MemoryManager.hpp
  include/dd/Package.hpp
  src/dd/CachedEdge.cpp
  src/dd/Complex.cpp
  src/dd/ComplexNumbers.cpp
  src/dd/ComplexValue.cpp
  src/dd/MemoryManager.cpp
  src/dd/Simulation.cpp
  test/dd/test_complex.cpp
Labels: enhancement, DD, c++

#458 ⚡ improve numerical accuracy of multiplication and division
  include/dd/Complex.hpp
  src/dd/Complex.cpp
  src/dd/ComplexNumbers.cpp
Labels: enhancement, DD, c++

#459 🐛 properly handle repeated cancellation in single-qubit gate fusion
  src/CircuitOptimizer.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: fix, Core, c++

#461 ⚡ improved collision logic in `RealNumberUniqueTable`
  include/dd/RealNumberUniqueTable.hpp
  src/dd/RealNumberUniqueTable.cpp
Labels: enhancement, DD, c++

#463 ⚡ fix performance regression for `RealNumber` computations
  src/dd/ComplexNumbers.cpp
  src/dd/ComplexValue.cpp
Labels: fix, DD, c++

#464 ✨ adopt ruff formatter
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement, dependencies, code quality

#467 🔧 Ruff config finetuning
  .pre-commit-config.yaml
  docs/quickstart.ipynb
  pyproject.toml
  src/mqt/core/_core/operations.pyi
  src/mqt/core/_core/symbolic.pyi
  src/mqt/core/plugins/qiskit.py
Labels: code quality, continuous integration

#465 ✨ equality comparison and hashing for operations and symbolic
  include/Definitions.hpp
  include/dd/Complex.hpp
  include/dd/ComputeTable.hpp
  include/dd/DDDefinitions.hpp
  include/dd/UniqueTable.hpp
  include/operations/ClassicControlledOperation.hpp
  include/operations/CompoundOperation.hpp
  include/operations/Expression.hpp
  include/operations/NonUnitaryOperation.hpp
  include/operations/Operation.hpp
  include/operations/SymbolicOperation.hpp
  include/zx/Rules.hpp
  include/zx/Simplify.hpp
  include/zx/Utils.hpp
  include/zx/ZXDefinitions.hpp
  include/zx/ZXDiagram.hpp
  src/dd/CachedEdge.cpp
  src/dd/ComplexValue.cpp
  src/dd/Edge.cpp
  src/mqt/core/_core/operations.pyi
  src/mqt/core/_core/symbolic.pyi
  src/python/operations/register_operation.cpp
  src/python/symbolic/register_expression.cpp
  src/python/symbolic/register_term.cpp
  src/python/symbolic/register_variable.cpp
  src/zx/FunctionalityConstruction.cpp
  src/zx/Rational.cpp
  src/zx/Rules.cpp
  src/zx/ZXDiagram.cpp
  test/unittests/test_qfr_functionality.cpp
  test/zx/test_rational.cpp
  test/zx/test_zx.cpp
  test/zx/test_zx_functionality.cpp
Labels: enhancement, Core, c++, python
