Repository munich-quantum-toolkit/core, pull requests merged in 2024-01, with the labels that each got.

#512 ✨ New optimization pass: Backpropagate output permutation and better dynamic circuit support
  include/CircuitOptimizer.hpp
  include/dd/Package.hpp
  include/dd/Simulation.hpp
  src/CircuitOptimizer.cpp
  src/QuantumComputation.cpp
  src/algorithms/BernsteinVazirani.cpp
  src/algorithms/QFT.cpp
  src/algorithms/QPE.cpp
  src/dd/Simulation.cpp
  test/CMakeLists.txt
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_bernsteinvazirani.cpp
  test/algorithms/test_qpe.cpp
  test/unittests/circuit_optimizer/test_backpropagate_output_permutation.cpp
Labels: feature, Core, c++

#514 ⬆️ update cibuildwheel version on Cirrus-CI
  .cirrus.yml
Labels: dependencies, packaging

#513 🚸 update maximum supported CMake version
  CMakeLists.txt
Labels: dependencies, c++

#516 🚨 fix warnings about exceptions that privately inherit from `std::exeption`
  include/parsers/qasm3_parser/Exception.hpp
Labels: code quality, c++

#517 🐛 avoid using system header includes for external dependencies
  eval/eval_dd_package.cpp
  include/dd/Benchmark.hpp
  include/dd/UniqueTable.hpp
  include/dd/statistics/PackageStatistics.hpp
  include/dd/statistics/Statistics.hpp
  include/python/pybind11.hpp
  include/python/qiskit/QuantumCircuit.hpp
  src/dd/statistics/MemoryManagerStatistics.cpp
  src/dd/statistics/Statistics.cpp
  src/dd/statistics/TableStatistics.cpp
  src/dd/statistics/UniqueTableStatistics.cpp
  src/python/operations/register_operation.cpp
  src/python/symbolic/register_expression.cpp
  test/algorithms/test_wstate.cpp
  test/dd/test_complex.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
  test/unittests/test_io.cpp
  test/zx/test_expression.cpp
  test/zx/test_rational.cpp
  test/zx/test_simplify.cpp
  test/zx/test_zx.cpp
  test/zx/test_zx_functionality.cpp
Labels: dependencies, fix, Core, c++

#518 📝 update documentation with OpenQASM 3.0 support
  docs/quickstart.ipynb
Labels: documentation, Core

#520 For builtin gates, print `c` prefix instead of `ctrl @ `
  include/operations/StandardOperation.hpp
  src/operations/StandardOperation.cpp
  test/unittests/test_qasm3_parser.cpp
Labels: enhancement, Core, c++

#521 🚸 OpenQASM string import and export
  docs/quickstart.ipynb
  include/Definitions.hpp
  include/QuantumComputation.hpp
  src/QuantumComputation.cpp
  src/mqt/core/_core/__init__.pyi
  src/mqt/core/_core/operations.pyi
  src/mqt/core/io.py
  src/python/operations/register_operation.cpp
  src/python/register_quantum_computation.cpp
  test/dd/test_dd_functionality.cpp
  test/python/test_io.py
  test/unittests/test_io.cpp
  test/unittests/test_qasm3_parser.cpp
  test/unittests/test_qfr_functionality.cpp
  test/zx/test_zx_functionality.cpp
Labels: enhancement, usability, Core, c++, python

#522 ⬆️ raise minimum required Boost version to 1.80
  cmake/ExternalDependencies.cmake
Labels: dependencies, ZX, c++

#523 🚸♻️ Improve the high-level DD package interfaces
  eval/eval_dd_package.cpp
  include/dd/FunctionalityConstruction.hpp
  include/dd/Operations.hpp
  include/dd/Simulation.hpp
  src/dd/Benchmark.cpp
  src/dd/FunctionalityConstruction.cpp
  src/dd/Operations.cpp
  src/dd/Simulation.cpp
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_bernsteinvazirani.cpp
  test/algorithms/test_grcs.cpp
  test/algorithms/test_qft.cpp
  test/algorithms/test_qpe.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/unittests/test_ecc_functionality.cpp
Labels: refactor, code quality, DD, c++

#524 🐛 Fix and optimize reduction of ancillaries
  include/dd/Package.hpp
  test/dd/test_package.cpp
Labels: fix, DD, c++

#525 🐛 Fix and optimize reduction of garbage
  include/dd/Package.hpp
  test/dd/test_package.cpp
Labels: fix, DD, c++

#526 🐛 fix missing `mcx` gate support in OpenQASM3 parser
  src/parsers/QASM3Parser.cpp
  test/unittests/test_qasm3_parser.cpp
Labels: fix, Core, c++

#528 🚸 Usability improvements for symbolic computations
  include/QuantumComputation.hpp
  include/operations/Expression.hpp
  include/operations/SymbolicOperation.hpp
  src/QuantumComputation.cpp
  src/mqt/core/_core/__init__.pyi
  src/mqt/core/_core/symbolic.pyi
  src/python/register_quantum_computation.cpp
  src/python/symbolic/register_expression.cpp
  test/unittests/test_symbolic.cpp
Labels: enhancement, usability, Core, c++

#529 ✨ Allow project installation
  CMakeLists.txt
  cmake/ExternalDependencies.cmake
  cmake/GetVersion.cmake
  cmake/StandardProjectSettings.cmake
  cmake/mqt-core-config.cmake.in
  pyproject.toml
  src/CMakeLists.txt
  src/dd/CMakeLists.txt
  src/ecc/CMakeLists.txt
  src/mqt/core/__init__.py
  src/mqt/core/__main__.py
  src/mqt/core/commands.py
  src/python/CMakeLists.txt
  src/zx/CMakeLists.txt
  test/python/test_cli.py
Labels: feature, minor, Core, packaging

#531 🩹 guard install instruction
  src/zx/CMakeLists.txt
Labels: fix, Core, c++

#532 Zero-ancilla partial equivalence checking
  include/dd/Package.hpp
  test/dd/test_package.cpp
Labels: enhancement, DD, c++

#535 📝 add configuration for offline doc formats
  .readthedocs.yaml
  README.md
  docs/conf.py
Labels: documentation

#536 🚨 ignore new pandas deprecation warning
  pyproject.toml
Labels: continuous integration

#534 :zap: Added native construction of two-target controlled-gate DDs
  include/dd/GateMatrixDefinitions.hpp
  include/dd/Operations.hpp
  include/dd/Package.hpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_package.cpp
Labels: enhancement, DD, c++

#541 ⏪ add `MQT::CorePython` target back
  include/mqt-core/python/qiskit/QuantumCircuit.hpp
  src/CMakeLists.txt
  src/python/qiskit/QuantumCircuit.cpp
Labels: fix, Core, c++
