Repository munich-quantum-toolkit/core, pull requests merged in 2024-03, with the labels that each got.

#560 🐛 Fix scientific notation in QASM import
  src/parsers/qasm3_parser/Scanner.cpp
  test/unittests/test_qasm3_parser.cpp
Labels: fix, Core, c++

#563 ♻️ Refactor garbage reduction
  include/mqt-core/QuantumComputation.hpp
  include/mqt-core/dd/Package.hpp
  src/QuantumComputation.cpp
  src/mqt/core/_core/__init__.pyi
  src/python/register_quantum_computation.cpp
  test/dd/test_package.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement, refactor, DD, c++

#566 ✨ add method for computing the conjugate of a vector DD
  include/mqt-core/dd/DDpackageConfig.hpp
  include/mqt-core/dd/Package.hpp
  test/dd/test_package.cpp
Labels: feature, DD, c++

#565 🚸 Improved usability for new magnitude addition functionality
  include/mqt-core/dd/DDpackageConfig.hpp
  include/mqt-core/dd/Package.hpp
Labels: usability, DD, c++

#568 🐛 fix check for density matrices in compute tables
  include/mqt-core/dd/ComputeTable.hpp
Labels: fix, DD, c++

#570 ⚡ optimize conjugate transpose in DD package
  include/mqt-core/dd/Package.hpp
Labels: enhancement, DD, c++

#569 🐛 Density matrix idenity handling
  include/mqt-core/dd/Node.hpp
  include/mqt-core/dd/Package.hpp
  test/dd/test_dd_noise_functionality.cpp
Labels: fix, DD, c++

#358 ✨ Removal of identity nodes in matrix DDs
  include/mqt-core/dd/CachedEdge.hpp
  include/mqt-core/dd/ComplexValue.hpp
  include/mqt-core/dd/Edge.hpp
  include/mqt-core/dd/Node.hpp
  include/mqt-core/dd/NoiseFunctionality.hpp
  include/mqt-core/dd/Operations.hpp
  include/mqt-core/dd/Package.hpp
  src/dd/Edge.cpp
  src/dd/FunctionalityConstruction.cpp
  src/dd/NoiseFunctionality.cpp
  src/dd/Operations.cpp
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_entanglement.cpp
  test/algorithms/test_grover.cpp
  test/algorithms/test_qft.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
Labels: feature, minor, DD, c++

#572 ♻️ streamline `makeTwoQubitGateDD` method
  include/mqt-core/dd/Operations.hpp
  include/mqt-core/dd/Package.hpp
  test/dd/test_package.cpp
Labels: enhancement, refactor, DD, c++

#574 ♻️ Eliminate `nqubits` and `startingQubit` from `Operation` class hierarchy
  docs/quickstart.ipynb
  eval/CMakeLists.txt
  include/mqt-core/QuantumComputation.hpp
  include/mqt-core/dd/Operations.hpp
  include/mqt-core/ecc/Ecc.hpp
  include/mqt-core/operations/ClassicControlledOperation.hpp
  include/mqt-core/operations/CompoundOperation.hpp
  include/mqt-core/operations/NonUnitaryOperation.hpp
  include/mqt-core/operations/Operation.hpp
  include/mqt-core/operations/StandardOperation.hpp
  include/mqt-core/operations/SymbolicOperation.hpp
  src/CircuitOptimizer.cpp
  src/QuantumComputation.cpp
  src/algorithms/GoogleRandomCircuitSampling.cpp
  src/dd/Operations.cpp
  src/dd/Simulation.cpp
  src/ecc/Q3Shor.cpp
  src/ecc/Q5Laflamme.cpp
  src/ecc/Q7Steane.cpp
  src/ecc/Q9Shor.cpp
  src/mqt/core/_core/operations.pyi
  src/mqt/core/io.py
  src/mqt/core/plugins/qiskit.py
  src/operations/CompoundOperation.cpp
  src/operations/NonUnitaryOperation.cpp
  src/operations/Operation.cpp
  src/operations/StandardOperation.cpp
  src/operations/SymbolicOperation.cpp
  src/parsers/QASM3Parser.cpp
  src/parsers/QCParser.cpp
  src/parsers/RealParser.cpp
  src/python/operations/register_compound_operation.cpp
  src/python/operations/register_non_unitary_operation.cpp
  src/python/operations/register_operation.cpp
  src/python/operations/register_standard_operation.cpp
  src/python/operations/register_symbolic_operation.cpp
  src/python/qiskit/QuantumCircuit.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/python/test_qiskit.py
  test/unittests/test_ecc_functionality.cpp
  test/unittests/test_io.cpp
  test/unittests/test_qfr_functionality.cpp
  test/zx/test_zx_functionality.cpp
Labels: refactor, Core, c++
