Repository munich-quantum-toolkit/core, pull requests merged in 2024-02, with the labels that each got.

#544 🚨 fix Qiskit 0.46.0 deprecation warnings
  pyproject.toml
  test/python/test_io.py
Labels: code quality, Core, python

#491 🧹 Noise-Aware Simulator Cleanup
  include/mqt-core/dd/NoiseFunctionality.hpp
  include/mqt-core/dd/Package.hpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
Labels: enhancement, refactor, minor, c++, python

#547 🎨 Misc. code quality improvements
  cmake/CompilerOptions.cmake
  src/parsers/qasm3_parser/passes/ConstEvalPass.cpp
  src/python/CMakeLists.txt
Labels: code quality, Core, c++

#548 🐛 ensure typeinfo and vtable information is present for `CompoundOperation`
  include/mqt-core/operations/CompoundOperation.hpp
  src/CMakeLists.txt
  src/operations/CompoundOperation.cpp
Labels: fix, Core, c++

#549 🐛 Fix `PiExpression` division and multiplication arithmetic
  include/mqt-core/operations/Expression.hpp
  test/zx/test_expression.cpp
Labels: fix, ZX, c++

#482 ✨ Add `XX-plus-YY` and `XX-minus-YY` gate support to ZX library
  include/mqt-core/operations/Expression.hpp
  include/mqt-core/zx/FunctionalityConstruction.hpp
  src/zx/FunctionalityConstruction.cpp
  test/zx/test_zx_functionality.cpp
Labels: enhancement, ZX, c++

#554 ⬆️ update scikit-build-core to 0.8.1
  noxfile.py
  pyproject.toml
  test/python/constraints.txt
Labels: dependencies, python, packaging

#556 ✨ Support for Qiskit 1.0
  pyproject.toml
  test/python/constraints.txt
Labels: dependencies, feature, minor, python

#553 🚚 Move from Cirrus CI back to GitHub Actions
  .cirrus.yml
  .github/workflows/reusable-cpp-tests-macos.yml
  .github/workflows/reusable-python-ci.yml
  .github/workflows/reusable-python-packaging.yml
  .github/workflows/reusable-python-tests.yml
  pyproject.toml
Labels: github_actions, continuous integration

#557 📝🎨 better dark mode docs
  docs/_static/custom.css
Labels: documentation

#558 🚸 allow using raw RST cells in jupyter notebooks
  .pre-commit-config.yaml
  docs/quickstart.ipynb
Labels: documentation, usability

#551 🩹 fixes for noise-aware simulation in DDSIM
  include/mqt-core/dd/DDpackageConfig.hpp
  include/mqt-core/dd/NoiseFunctionality.hpp
  src/dd/FunctionalityConstruction.cpp
  src/dd/NoiseFunctionality.cpp
  test/dd/test_dd_noise_functionality.cpp
Labels: fix, DD, c++
