Repository munich-quantum-toolkit/core, pull requests merged in 2024-06, with the labels that each got.

#621 Moved symmetric matrix to datastructures
  include/mqt-core/datastructures/SymmetricMatrix.hpp
  test/datastructures/test_symmetric_matrix.cpp
Labels: enhancement, Core, c++

#622 🚸 new test macro with customizable working directory
  cmake/PackageAddTest.cmake
Labels: usability, Core, c++

#624 Generalize concept of removing OpTypes
  include/mqt-core/CircuitOptimizer.hpp
  src/CircuitOptimizer.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement, Core, c++

#625 🎨🚨 Improved formatting and linting config
  .editorconfig
  .git_archival.txt
  .pre-commit-config.yaml
  include/mqt-core/QuantumComputation.hpp
  include/mqt-core/dd/Package.hpp
  include/mqt-core/na/NADefinitions.hpp
  include/mqt-core/operations/ClassicControlledOperation.hpp
  pyproject.toml
  src/QuantumComputation.cpp
  src/mqt/core/plugins/qiskit.py
  src/operations/ClassicControlledOperation.cpp
  src/parsers/QASM3Parser.cpp
  src/zx/ZXDiagram.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/na/test_nadefinitions.cpp
  test/test_operation.cpp
  test/unittests/circuit_optimizer/test_elide_permutations.cpp
  test/unittests/test_qasm3_parser.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: dependencies, code quality, continuous integration

#626 🩹 make sure to use the install rpath for build
  src/CMakeLists.txt
Labels: fix, c++

#627 ✨ add an export header to explicitly manage symbol visibility
  src/CMakeLists.txt
Labels: enhancement, Core, c++

#629 🚸 Support for adding tests to NALAC
  include/mqt-core/Permutation.hpp
  include/mqt-core/na/NAComputation.hpp
  include/mqt-core/na/NADefinitions.hpp
  include/mqt-core/na/operations/NAGlobalOperation.hpp
  include/mqt-core/operations/CompoundOperation.hpp
  include/mqt-core/operations/NonUnitaryOperation.hpp
  include/mqt-core/operations/Operation.hpp
  src/na/NAComputation.cpp
  src/na/operations/NALocalOperation.cpp
  src/operations/CompoundOperation.cpp
  src/operations/Operation.cpp
  test/datastructures/test_layer.cpp
  test/na/test_nacomputation.cpp
  test/na/test_naoperation.cpp
  test/test_operation.cpp
  test/unittests/test_qfr_functionality.cpp
Labels: enhancement, Core, c++

#631 ⚡🔧 Faster `cibuildwheel` and better Windows wheel repair
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies, github_actions, continuous integration

#628 Improvements for Trace Computation
  include/mqt-core/dd/DDpackageConfig.hpp
  include/mqt-core/dd/Package.hpp
  test/dd/test_package.cpp
Labels: enhancement, DD, c++

#637 🚨🩹 fix the ruff `banned-api` configuration
  pyproject.toml
Labels: code quality, continuous integration, python

#638 📦 add artifact attestation
  .github/workflows/cd.yml
Labels: continuous integration, python, packaging
