Repository munich-quantum-toolkit/core, pull requests merged in 2025-05, with the labels that each got.

#952 :construction_worker: add windows CI for MLIR
  .github/workflows/ci_mlir.yml
Labels: continuous integration, MLIR

#961 🚸 add convenience macro for adding MQT Core libraries
  CMakeLists.txt
  cmake/AddMQTCoreLibrary.cmake
  src/algorithms/CMakeLists.txt
  src/circuit_optimizer/CMakeLists.txt
  src/datastructures/CMakeLists.txt
  src/dd/CMakeLists.txt
  src/ir/CMakeLists.txt
  src/na/CMakeLists.txt
  src/qasm3/CMakeLists.txt
  src/zx/CMakeLists.txt
Labels: usability, c++

#962 🚸 Add dedicated option for only building MQT Core as shared libraries
  CMakeLists.txt
  pyproject.toml
  src/algorithms/CMakeLists.txt
  src/circuit_optimizer/CMakeLists.txt
  src/datastructures/CMakeLists.txt
  src/dd/CMakeLists.txt
  src/ir/CMakeLists.txt
  src/na/CMakeLists.txt
  src/qasm3/CMakeLists.txt
  src/zx/CMakeLists.txt
Labels: usability, c++

#963 🚸 add dedicated MLIR setup file
  CMakeLists.txt
  cmake/SetupMLIR.cmake
  mlir/CMakeLists.txt
Labels: usability, c++, MLIR

#948 ⚗️ Testing functionality of MQTOpt value dialect
  mlir/test/Dialect/MQTOpt/IR/bell_state_value_dialect.mlir
  mlir/test/Dialect/MQTOpt/IR/dialect_features.mlir
Labels: c++, MLIR

#953 🎨 Restructure README.md and index.md
  README.md
  docs/_templates/page.html
  docs/conf.py
  docs/index.md
Labels: documentation

#908 ✨ Migrate and Refactor Approximation Functionality from DDSim Package
  CHANGELOG.md
  include/mqt-core/dd/Approximation.hpp
  src/dd/Approximation.cpp
  test/dd/test_approximations.cpp
Labels: refactor, feature, DD, c++
