Repository munich-quantum-toolkit/core, pull requests merged in 2025-03, with the labels that each got.

#847 ⬆️ scikit-build-core 0.11, PEP 639 license expressions, sphinx fixes, more automerge
  .github/renovate.json5
  noxfile.py
  pyproject.toml
  uv.lock
Labels: dependencies, Core, python

#849 🔧 Handle empty quantum and classical registers in qiskit to MQT translation
  src/mqt/core/plugins/qiskit.py
  test/python/plugins/test_qiskit.py
Labels: fix, Core, python

#850 🐛 Fix and enhance Qiskit layout and permutation handling
  src/mqt/core/ir/__init__.pyi
  src/mqt/core/plugins/qiskit.py
  src/python/ir/register_permutation.cpp
  test/python/plugins/test_qiskit.py
Labels: fix, Core, c++, python

#851 📝 Slightly improve code documentation and `QuantumComputation.__repr__`
  include/mqt-core/Definitions.hpp
  include/mqt-core/dd/FunctionalityConstruction.hpp
  include/mqt-core/dd/Operations.hpp
  include/mqt-core/dd/Simulation.hpp
  include/mqt-core/ir/operations/Control.hpp
  src/python/ir/register_quantum_computation.cpp
Labels: documentation, Core, c++, python

#846 🎨 Refactor `NAComputation` with concrete base classes for every operation and ouput new `.naviz` format
  .clang-tidy
  include/mqt-core/ir/operations/CompoundOperation.hpp
  include/mqt-core/ir/operations/Operation.hpp
  include/mqt-core/ir/operations/StandardOperation.hpp
  include/mqt-core/na/NAComputation.hpp
  include/mqt-core/na/NADefinitions.hpp
  include/mqt-core/na/entities/Atom.hpp
  include/mqt-core/na/entities/Location.hpp
  include/mqt-core/na/entities/Zone.hpp
  include/mqt-core/na/operations/GlobalCZOp.hpp
  include/mqt-core/na/operations/GlobalOp.hpp
  include/mqt-core/na/operations/GlobalRYOp.hpp
  include/mqt-core/na/operations/LoadOp.hpp
  include/mqt-core/na/operations/LocalOp.hpp
  include/mqt-core/na/operations/LocalRZOp.hpp
  include/mqt-core/na/operations/MoveOp.hpp
  include/mqt-core/na/operations/NAGlobalOperation.hpp
  include/mqt-core/na/operations/NALocalOperation.hpp
  include/mqt-core/na/operations/NAOperation.hpp
  include/mqt-core/na/operations/NAShuttlingOperation.hpp
  include/mqt-core/na/operations/Op.hpp
  include/mqt-core/na/operations/ShuttlingOp.hpp
  include/mqt-core/na/operations/StoreOp.hpp
  src/ir/operations/CompoundOperation.cpp
  src/ir/operations/StandardOperation.cpp
  src/na/CMakeLists.txt
  src/na/NAComputation.cpp
  src/na/operations/GlobalOp.cpp
  src/na/operations/LoadOp.cpp
  src/na/operations/LocalOp.cpp
  src/na/operations/MoveOp.cpp
  src/na/operations/NALocalOperation.cpp
  src/na/operations/NAShuttlingOperation.cpp
  src/na/operations/StoreOp.cpp
  test/ir/test_operation.cpp
  test/na/test_nacomputation.cpp
  test/na/test_nadefinitions.cpp
  test/na/test_naoperation.cpp
Labels: enhancement, usability, refactor, c++

#858 ♻️🐛 Refactor `qc::Permutation` and fix corner case in Qiskit layout import
  include/mqt-core/ir/Permutation.hpp
  src/ir/QuantumComputation.cpp
  src/mqt/core/ir/__init__.pyi
  src/mqt/core/plugins/qiskit.py
  src/python/ir/register_permutation.cpp
  src/qasm3/Parser.cpp
  src/qasm3/passes/TypeCheckPass.cpp
Labels: code quality, fix, Core, c++

#859 ✨ Add Python interface improvements and Qiskit export support
  include/mqt-core/ir/operations/CompoundOperation.hpp
  pyproject.toml
  src/mqt/core/ir/__init__.pyi
  src/mqt/core/ir/operations.pyi
  src/mqt/core/plugins/qiskit/__init__.py
  src/mqt/core/plugins/qiskit/mqt_to_qiskit.py
  src/mqt/core/plugins/qiskit/qiskit_to_mqt.py
  src/python/ir/operations/register_compound_operation.cpp
  src/python/ir/register_permutation.cpp
  src/python/ir/register_quantum_computation.cpp
  src/python/ir/register_registers.cpp
  test/python/plugins/test_qiskit.py
Labels: feature, fix, Core, python

#861 📝 Update documentation to reflect recent changes
  docs/DevelopmentGuide.md
  docs/conf.py
Labels: documentation

#867 Update paper.bib
  paper/paper.bib
Labels: documentation

#869 📝 Add JOSS paper
  .pre-commit-config.yaml
  paper/codemeta.json
  paper/paper.bib
  paper/paper.md
  pyproject.toml
Labels: documentation

#860 ✨Add continuous testing workflow for Qiskit main branch
  .github/workflows/upstream.yml
  noxfile.py
Labels: continuous integration, Core, python, github-actions

#870 🩹 Add `insert_or_assign` method to `Permutation` class
  include/mqt-core/ir/Permutation.hpp
Labels: fix, Core, c++

#873 ⚗️ Fix potential division by zero error and tweak DD evaluation settings
  eval/eval_dd_package.cpp
  src/mqt/core/dd_evaluation.py
Labels: enhancement, DD, c++

#866 ♻️ Remove template parameter from MemoryManager and adjacent classes
  include/mqt-core/dd/CachedEdge.hpp
  include/mqt-core/dd/Edge.hpp
  include/mqt-core/dd/LinkedListBase.hpp
  include/mqt-core/dd/MemoryManager.hpp
  include/mqt-core/dd/Node.hpp
  include/mqt-core/dd/Package.hpp
  include/mqt-core/dd/RealNumber.hpp
  include/mqt-core/dd/RealNumberUniqueTable.hpp
  include/mqt-core/dd/UniqueTable.hpp
  include/mqt-core/dd/statistics/MemoryManagerStatistics.hpp
  src/dd/CachedEdge.cpp
  src/dd/Edge.cpp
  src/dd/MemoryManager.cpp
  src/dd/RealNumber.cpp
  src/dd/RealNumberUniqueTable.cpp
  src/dd/UniqueTable.cpp
  src/dd/statistics/MemoryManagerStatistics.cpp
  test/dd/test_complex.cpp
  test/dd/test_package.cpp
Labels: refactor, code quality, DD, c++

#877 🎨 Add U operation and allow for Multiple Zones
  include/mqt-core/na/NAComputation.hpp
  include/mqt-core/na/entities/Location.hpp
  include/mqt-core/na/entities/Zone.hpp
  include/mqt-core/na/operations/GlobalCZOp.hpp
  include/mqt-core/na/operations/GlobalOp.hpp
  include/mqt-core/na/operations/GlobalRYOp.hpp
  include/mqt-core/na/operations/LocalRZOp.hpp
  include/mqt-core/na/operations/LocalUOp.hpp
  src/na/NAComputation.cpp
  src/na/entities/Zone.cpp
  src/na/operations/GlobalOp.cpp
  src/na/operations/LocalOp.cpp
  test/na/test_nacomputation.cpp
Labels: enhancement, c++, NA

#882 🔥 Remove `Teleportation` gate
  include/mqt-core/ir/operations/OpType.inc
  include/mqt-core/ir/operations/StandardOperation.hpp
  include/mqt-core/qasm3/StdGates.hpp
  src/ir/QuantumComputation.cpp
  src/ir/operations/OpType.cpp
  src/ir/operations/StandardOperation.cpp
  src/mqt/core/ir/operations.pyi
  src/python/ir/operations/register_optype.cpp
  test/ir/test_qasm3_parser.cpp
  test/ir/test_qfr_functionality.cpp
Labels: refactor, Core, c++

#883 🔥 Remove `extract_probability_vector` functionality
  include/mqt-core/dd/Simulation.hpp
  src/dd/Simulation.cpp
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_qpe.cpp
  test/dd/test_dd_functionality.cpp
Labels: refactor, DD, c++

#886 ♻️ Eliminate templates from `dd::Package` class
  eval/eval_dd_package.cpp
  include/mqt-core/dd/ComputeTable.hpp
  include/mqt-core/dd/DDpackageConfig.hpp
  include/mqt-core/dd/DensityNoiseTable.hpp
  include/mqt-core/dd/Export.hpp
  include/mqt-core/dd/FunctionalityConstruction.hpp
  include/mqt-core/dd/Node.hpp
  include/mqt-core/dd/NoiseFunctionality.hpp
  include/mqt-core/dd/Operations.hpp
  include/mqt-core/dd/Package.hpp
  include/mqt-core/dd/Package_fwd.hpp
  include/mqt-core/dd/Simulation.hpp
  include/mqt-core/dd/StochasticNoiseOperationTable.hpp
  include/mqt-core/dd/UnaryComputeTable.hpp
  include/mqt-core/dd/UniqueTable.hpp
  include/mqt-core/dd/statistics/PackageStatistics.hpp
  src/dd/Export.cpp
  src/dd/FunctionalityConstruction.cpp
  src/dd/NoiseFunctionality.cpp
  src/dd/Operations.cpp
  src/dd/Package.cpp
  src/dd/Simulation.cpp
  src/dd/statistics/PackageStatistics.cpp
  src/mqt/core/dd.pyi
  src/python/dd/register_dd.cpp
  src/python/dd/register_dd_package.cpp
  test/algorithms/eval_dynamic_circuits.cpp
  test/algorithms/test_bernsteinvazirani.cpp
  test/algorithms/test_entanglement.cpp
  test/algorithms/test_grover.cpp
  test/algorithms/test_qft.cpp
  test/algorithms/test_qpe.cpp
  test/algorithms/test_random_clifford.cpp
  test/algorithms/test_statepreparation.cpp
  test/algorithms/test_wstate.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_edge_functionality.cpp
  test/dd/test_package.cpp
Labels: refactor, major, DD, c++
