Repository munich-quantum-toolkit/core, pull requests merged in 2025-07, with the labels that each got.

#1020 ♻️ Switch from reference counting to mark-and-sweep garbage collection in decision diagram package
  CHANGELOG.md
  bindings/dd/register_dd_package.cpp
  eval/eval_dd_package.cpp
  include/mqt-core/dd/Complex.hpp
  include/mqt-core/dd/ComplexNumbers.hpp
  include/mqt-core/dd/DDDefinitions.hpp
  include/mqt-core/dd/Edge.hpp
  include/mqt-core/dd/Export.hpp
  include/mqt-core/dd/Node.hpp
  include/mqt-core/dd/Package.hpp
  include/mqt-core/dd/RealNumber.hpp
  include/mqt-core/dd/RealNumberUniqueTable.hpp
  include/mqt-core/dd/UniqueTable.hpp
  include/mqt-core/dd/statistics/PackageStatistics.hpp
  include/mqt-core/dd/statistics/UniqueTableStatistics.hpp
  src/dd/Complex.cpp
  src/dd/ComplexNumbers.cpp
  src/dd/Edge.cpp
  src/dd/Operations.cpp
  src/dd/Package.cpp
  src/dd/RealNumber.cpp
  src/dd/RealNumberUniqueTable.cpp
  src/dd/UniqueTable.cpp
  src/dd/statistics/PackageStatistics.cpp
  src/dd/statistics/UniqueTableStatistics.cpp
  test/algorithms/test_grover.cpp
  test/algorithms/test_qft.cpp
  test/dd/test_complex.cpp
  test/dd/test_dd_functionality.cpp
  test/dd/test_dd_noise_functionality.cpp
  test/dd/test_package.cpp
Labels: enhancement, DD, c++

#1039 🎨 Stop pre-commit if there are merge conflicts
  .pre-commit-config.yaml
Labels: pre-commit

#1044 🔥 do not eagerly import Qiskit plugin
  python/mqt/core/plugins/__init__.py
Labels: fix, Core, python

#1045 👷 Update templating workflow to use v1.0.0
  .github/workflows/templating.yml
Labels: continuous integration

#1050 ⬆️ raise `pybind11` lower bound to `v3.0.0`
  .github/workflows/ci.yml
  cmake/ExternalDependencies.cmake
  pyproject.toml
  uv.lock
Labels: dependencies, python

#1042 🐛 Fix parsing of `GPhase`
  CHANGELOG.md
  mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptDialect.h
  mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptOps.td
  mlir/lib/Dialect/MQTOpt/IR/MQTOptOps.cpp
  mlir/test/Dialect/MQTDyn/IR/dialect_features.mlir
  mlir/test/Dialect/MQTOpt/IR/dialect_features.mlir
Labels: fix, Core, MLIR

#1056 ♻️ one more `match` and `rewrite` replacement
  mlir/lib/Dialect/MQTOpt/Transforms/MergeRotationGatesPattern.cpp
Labels: fix, c++, MLIR

#1049 ⬆️ Update CI/CD testing configuration
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/upstream.yml
Labels: continuous integration

#1060 🐛👷 Fix condition for Python coverage
  .github/workflows/ci.yml
Labels: continuous integration, fix

#1062 👷 Always test selected Debug builds
  .github/workflows/ci.yml
  .github/workflows/upstream.yml
Labels: continuous integration, c++

#1061 👷 Update workflow that creates issue if Qiskit upstream tests fail
  .github/workflows/upstream.yml
Labels: continuous integration

#1059 🧪 Add additional tests to improve coverage
  mlir/lib/Dialect/MQTOpt/Transforms/CancelConsecutiveInversesPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/MergeRotationGatesPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/ToQuantumComputationPattern.cpp
  mlir/test/Dialect/MQTDyn/IR/dialect_features.mlir
  mlir/test/Dialect/MQTDyn/Transforms/constant-folding.mlir
  mlir/test/Dialect/MQTOpt/IR/dialect_features.mlir
  mlir/test/Dialect/MQTOpt/Transforms/merge-rotation-gates.mlir
  mlir/test/Dialect/MQTOpt/Transforms/to-quantum-computation.mlir
Labels: code quality, c++, MLIR

#1077 ✨ Make Python enums PEP-435 compatible
  CHANGELOG.md
  UPGRADING.md
  bindings/dd/register_dd_package.cpp
  bindings/ir/operations/register_classic_controlled_operation.cpp
  bindings/ir/operations/register_control.cpp
  bindings/ir/operations/register_optype.cpp
  python/mqt/core/dd.pyi
  python/mqt/core/ir/operations.pyi
Labels: enhancement, refactor, c++, python

#1086 🔖 Prepare release of v3.2.0
  CHANGELOG.md
  UPGRADING.md
Labels: documentation

#1088 🐛 Fix bug in DD package
  include/mqt-core/dd/Package.hpp
Labels: fix, c++
