Repository munich-quantum-toolkit/core, pull requests merged in 2025-04, with the labels that each got.

#893 Clean Up mqt-core round-trip pass
  mlir/lib/Dialect/MQTOpt/Transforms/FromQuantumComputationPattern.cpp
  mlir/test/Dialect/MQTOpt/Transforms/to-quantum-computation.mlir
Labels: code quality, c++, MLIR

#895 :building_construction: Enforce LLVM-20 when building MLIR subdirectory
  .github/workflows/ci_mlir.yml
  mlir/CMakeLists.txt
  mlir/lib/Dialect/MQTOpt/Transforms/MQTCoreRoundTrip.cpp
Labels: dependencies, continuous integration, MLIR

#901 🐛 restore installation of Boost multiprecision headers
  src/zx/CMakeLists.txt
Labels: fix, ZX, c++

#902 🎨 slightly touch up template instantiations and use more trailing return types
  include/mqt-core/dd/CachedEdge.hpp
  include/mqt-core/dd/Edge.hpp
  src/dd/CachedEdge.cpp
  src/dd/Edge.cpp
Labels: code quality, DD, c++

#906 🔧 Minor updates for CMake configuration
  CMakeLists.txt
  cmake/ExternalDependencies.cmake
Labels: code quality, c++

#907 ⬆️ update lower bounds of dev dependencies
  pyproject.toml
  uv.lock
Labels: dependencies, python

#909 ✨📝 Add changelog and upgrade guide infrastructure
  .github/contributing.md
  .github/release-drafter.yml
  CHANGELOG.md
  UPGRADING.md
  docs/CHANGELOG.md
  docs/UPGRADING.md
  docs/index.md
Labels: documentation

#915 🎨 Add Helper Functions For `simulate` And `sample`
  include/mqt-core/dd/Operations.hpp
  include/mqt-core/ir/QuantumComputation.hpp
  src/dd/Operations.cpp
  src/dd/Simulation.cpp
Labels: code quality, DD, c++

#921 ⬆️ update nlohmann_json to `v3.12.0`
  CHANGELOG.md
  cmake/ExternalDependencies.cmake
Labels: dependencies, c++

#930 🐛 Fix sxdg support in qiskit import
  CHANGELOG.md
  src/mqt/core/plugins/qiskit/qiskit_to_mqt.py
  test/python/plugins/test_qiskit.py
Labels: fix, Core, python

#934 ⏪️ [MLIR] Bring back MLIR / LLVM 19.0 support
  .github/workflows/ci_mlir.yml
  CHANGELOG.md
  mlir/CMakeLists.txt
  mlir/include/mlir/Dialect/Common/Compat.h
  mlir/lib/Dialect/MQTDyn/Transforms/ConstantFolding.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/CancelConsecutiveInverses.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/MQTCoreRoundTrip.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/QuantumSinkPass.cpp
Labels: fix, MLIR

#931 ♻️ [MLIR] Unify Operands and Results and add Docs Page for MLIR
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/index.md
  docs/mlir.md
  mlir/include/mlir/Dialect/Common/IR/CommonTraits.h
  mlir/include/mlir/Dialect/MQTDyn/IR/MQTDynInterfaces.td
  mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptInterfaces.td
  mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptOps.td
  mlir/lib/Dialect/MQTOpt/Transforms/CancelConsecutiveInversesPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/FromQuantumComputationPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/QuantumSinkPushPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/QuantumSinkShiftPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/ToQuantumComputationPattern.cpp
  mlir/test/Dialect/MQTOpt/IR/bell_state_value_dialect.mlir
  mlir/test/Dialect/MQTOpt/Transforms/consecutive-inverses.mlir
  mlir/test/Dialect/MQTOpt/Transforms/to-quantum-computation.mlir
Labels: refactor, MLIR

#933 ♻️ [MLIR] Reduce Redundancy in Operation Definition
  CHANGELOG.md
  mlir/include/mlir/Dialect/Common/IR/StdOps.td.inc
  mlir/include/mlir/Dialect/MQTDyn/IR/CMakeLists.txt
  mlir/include/mlir/Dialect/MQTDyn/IR/MQTDynInterfaces.td
  mlir/include/mlir/Dialect/MQTDyn/IR/MQTDynOps.td
  mlir/include/mlir/Dialect/MQTOpt/IR/CMakeLists.txt
  mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptInterfaces.td
  mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptOps.td
  mlir/lib/Dialect/MQTDyn/Transforms/ConstantFoldExtractQubitPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/FromQuantumComputationPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/ToQuantumComputationPattern.cpp
  mlir/test/Dialect/MQTOpt/IR/bell_state_value_dialect.mlir
Labels: refactor, MLIR

#932 🐛 [MLIR] Fix bug in MLIR round-trip
  CHANGELOG.md
  mlir/lib/Dialect/MQTOpt/Transforms/FromQuantumComputationPattern.cpp
  mlir/lib/Dialect/MQTOpt/Transforms/ToQuantumComputationPattern.cpp
  mlir/test/Dialect/MQTOpt/Transforms/to-quantum-computation.mlir
Labels: fix, MLIR

#937 🩹 Fix MLIR workflow
  .github/workflows/ci_mlir.yml
Labels: continuous integration, fix

#938 📝 Update templates and license tools configuration
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
  .license-tools-config.json
  pyproject.toml
Labels: documentation, continuous integration

#926 👷 Add Windows 11 ARM runners
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/upstream.yml
  CHANGELOG.md
  CMakeLists.txt
  noxfile.py
  pyproject.toml
Labels: continuous integration

#942 📝 Refine changelog
  CHANGELOG.md
  docs/conf.py
Labels: documentation
